package com.ecommerce.microcommerce;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class MicrocommerceApplication {

    //docs generated by swagger in: http://localhost:9090/v2/api-docs (JSON)
    // and http://localhost:9090/swagger-ui.html
	public static void main(String[] args) {
		SpringApplication.run(MicrocommerceApplication.class, args);
	}
}
